name: publish-to-itch

on:
  release:
    types: [published]

jobs:
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # separate step to extract the version from the tag name
      - name: get tag from version
        id: tag_version
        run: |
          echo ::set-output name=TAG_VERSION::${GITHUB_REF#refs/tags/v}

      - uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_IO_API_KEY }}
          CHANNEL: web
          ITCH_GAME: ludum-dare-game-2022-04
          ITCH_USER: ulm-awesome
          PACKAGE: HTML5.zip
          VERSION: ${{ steps.tag_version.outputs.TAG_VERSION }}
